# Generated by Django 3.1.1 on 2020-10-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201017_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='things',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
